services:

  app:
    image: profolio-app:latest
    container_name: profolio-app
    restart: unless-stopped
    ports:
      - "81:81"
    networks:
      - profolio-network


  ngrok:
    image: ngrok/ngrok:latest
    container_name: profolio-ngrok
    restart: unless-stopped

    depends_on:
      - app

    env_file:
      - .env.ngrok

    command:
      - "http"
      - "app:81"

    ports:
      - "4040:4040"

    networks:
      - profolio-network


networks:
  profolio-network:
    external: true
    name: profolio-net