services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: jenkins

    user: root

    restart: unless-stopped

    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - jenkins-network
      - profolio-network


volumes:
  jenkins_home:


networks:
  jenkins-network:
    driver: bridge

  profolio-network:
    external: true
    name: profolio-net